create table pbp (
GameId varchar(30)
,GameDate DATE
,Quarter int
,Minute int
,Second int
,OffenseTeam varchar(5)
,DefenseTeam varchar(5)
,Down int
,ToGo int
,YardLine int
,SeriesFirstDown int
,NextScore int
,Description varchar(100)
,TeamWin int
,SeasonYear int
,Yards int
,Formation varchar(50)
,PlayType varchar(30)
,IsRush boolean
,IsPass boolean
,IsIncomplete boolean
,IsTouchdown boolean
,PassType varchar(30)
,IsSack boolean
,IsChallenge boolean
,IsChallengeReversed boolean
,Challenger varchar(10)
,IsMeasurement boolean
,IsInterception boolean
,IsFumble boolean
,IsPenalty boolean
,IsTwoPointConversion boolean
,IsTwoPointConversionSuccessful boolean
,RushDirection varchar(30)
,YardLineFixed int
,YardLineDirection varchar(10)
,IsPenaltyAccepted boolean
,PenaltyTeam varchar(5)
,IsNoPlay boolean
,PenaltyType varchar(30)
,PenaltyYards int
)